language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.0
  - 5.6

env:
  matrix:
    - PHPUNIT=4
    - PHPUNIT=5
    - PHPUNIT=6

matrix:
  exclude:
    - php: 5.6
      env: PHPUNIT=6

install:
  - composer require --prefer-dist --dev phpunit/phpunit:^$PHPUNIT
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit
